version: '3.8'

services:
  db:
    image: mysql:8.0
    env_file: .env
    ports:
      - ${DB_PORT}:3306
    volumes:
      - db-vol:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: 'mysqladmin ping -h localhost -u root -p${MYSQL_ROOT_PASSWORD}'
      interval: 300s
      timeout: 300s
      retries: 60

  adminer:
    container_name: adminer
    hostname: adminer
    image: adminer
    restart: always
    env_file:
      - .env
    ports:
      - ${ADMINER_PORT}:8080

  api:
    container_name: api
    build:
      context: ./post-api
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - ${API_PORT}:3001
    restart: unless-stopped
    volumes:
      - ./post-app:/app/
      - /app/node_modules
    command: bash -c "yarn run start:dev"

  # client:
  #   build: ./post-client
  #   ports:
  #     - "${CLIENT_PORT}:3000"
  #   depends_on:
  #     - api
  #   env_file:
  #     - .env
  #   restart: unless-stopped
  #   volumes:
  #     - ./post-client:/app/
  #     - /app/node_modules
  #   command: bash -c "yarn start"

volumes:
  db-vol:
